language: haskell

before_install:
  - make ghc-head

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test --test-options='-a 100'

after_script:
  - cat dist/test/units-*-spec.log 
